### ISSUE TITLE
Import of ArchPy fails  (windows 11 - miniconda) - Missing geos_c.dll?

### ISSUE THREAD

**Issue by cultpenguin** [randlab/ArchPy#2]
After doing a "pip install geoarchpy" I get the following error (related to a missing geos_c.dll I believe) when importing ArchPy: 

              (archpy) c:\Users\thoma\miniconda3\envs\archpy>python
              Python 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)] on win32
              Type "help", "copyright", "credits" or "license" for more information.
              >>> import ArchPy
              Traceback (most recent call last):
                File "<stdin>", line 1, in <module>
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\site-packages\ArchPy\__init__.py", line 1, in <module>
                  import ArchPy.base
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\site-packages\ArchPy\base.py", line 11, in <module>
                  import shapely.geometry
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
                  from .base import CAP_STYLE, JOIN_STYLE
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\site-packages\shapely\geometry\base.py", line 19, in <module>
                  from shapely.coords import CoordinateSequence
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\site-packages\shapely\coords.py", line 8, in <module>
                  from shapely.geos import lgeos
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\site-packages\shapely\geos.py", line 149, in <module>
                  _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
                File "c:\Users\thoma\miniconda3\envs\archpy\lib\ctypes\__init__.py", line 374, in __init__
                  self._handle = _dlopen(self._name, mode)
              FileNotFoundError: Could not find module 'c:\Users\thoma\miniconda3\envs\archpy\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by LudovicSchorpp** [comment]
Hello Thomas ! 

I just saw your issue now. Apparently the problem is coming from shapely, a package to deal with shapefiles and polygon in python. Thank you for pointing this issue. For now I don't really know why it is happening. Apparently it is due to this library that is not accessible for shapely. I think an update of the version of shapely will work but I have to investigate a little bit more. I will make an update as soon as possible.

Thank you again !
